export const STUDENT_OBJECTS = [
  {
    id: 1,
    name: "Alice",
    role: "Student",
    class_id: "101",
    department: "Medicine",
    created_date: "2025-01-01",
    status: "active",
    email: "alice@example.com",
    phone: "+1234567890",
  },
  {
    id: 2,
    name: "Bob",
    role: "Student",
    class_id: "102",
    department: "Law",
    created_date: "2025-01-02",
    status: "active",
    email: "bob@example.com",
    phone: "+1234567891",
  },
  {
    id: 3,
    name: "Charlie",
    role: "Student",
    class_id: "103",
    department: "Engineering",
    created_date: "2025-01-03",
    status: "away",
    email: "charlie@example.com",
    phone: "+1234567892",
  },
  {
    id: 4,
    name: "David",
    role: "Student",
    class_id: "104",
    department: "Medicine",
    created_date: "2025-01-04",
    status: "offline",
    email: "david@example.com",
    phone: "+1234567893",
  },
  {
    id: 5,
    name: "Eva",
    role: "Student",
    class_id: "105",
    department: "Law",
    created_date: "2025-01-05",
    status: "active",
    email: "eva@example.com",
    phone: "+1234567894",
  },
  {
    id: 6,
    name: "Frank",
    role: "Student",
    class_id: "106",
    department: "Engineering",
    created_date: "2025-01-06",
    status: "active",
    email: "frank@example.com",
    phone: "+1234567895",
  },
  {
    id: 7,
    name: "Grace",
    role: "Student",
    class_id: "107",
    department: "Medicine",
    created_date: "2025-01-07",
    status: "away",
    email: "grace@example.com",
    phone: "+1234567896",
  },
  {
    id: 8,
    name: "Hank",
    role: "Student",
    class_id: "108",
    department: "Law",
    created_date: "2025-01-08",
    status: "offline",
    email: "hank@example.com",
    phone: "+1234567897",
  },
  {
    id: 9,
    name: "Ivy",
    role: "Student",
    class_id: "109",
    department: "Engineering",
    created_date: "2025-01-09",
    status: "active",
    email: "ivy@example.com",
    phone: "+1234567898",
  },
  {
    id: 10,
    name: "Jack",
    role: "Student",
    class_id: "110",
    department: "Medicine",
    created_date: "2025-01-10",
    status: "active",
    email: "jack@example.com",
    phone: "+1234567899",
  },
];

export const TUTOR_OBJECTS = [
  {
    id: 1,
    name: "Dr. Smith",
    role: "Tutor",
    department: "Medicine",
    created_date: "2020-01-01",
    status: "active",
    current_year: 5,
    current_students: 10,
    email: "dr.smith@example.com",
    phone: "+9876543210",
  },
  {
    id: 2,
    name: "Prof. Johnson",
    role: "Tutor",
    department: "Law",
    created_date: "2020-02-01",
    status: "active",
    current_year: 3,
    current_students: 12,
    email: "prof.johnson@example.com",
    phone: "+9876543211",
  },
  {
    id: 3,
    name: "Mr. Williams",
    role: "Tutor",
    department: "Engineering",
    created_date: "2020-03-01",
    status: "away",
    current_year: 2,
    current_students: 8,
    email: "mr.williams@example.com",
    phone: "+9876543212",
  },
  {
    id: 4,
    name: "Dr. Brown",
    role: "Tutor",
    department: "Medicine",
    created_date: "2020-04-01",
    status: "offline",
    current_year: 4,
    current_students: 15,
    email: "dr.brown@example.com",
    phone: "+9876543213",
  },
  {
    id: 5,
    name: "Prof. Davis",
    role: "Tutor",
    department: "Law",
    created_date: "2020-05-01",
    status: "active",
    current_year: 3,
    current_students: 14,
    email: "prof.davis@example.com",
    phone: "+9876543214",
  },
  {
    id: 6,
    name: "Mr. Martinez",
    role: "Tutor",
    department: "Engineering",
    created_date: "2020-06-01",
    status: "away",
    current_year: 1,
    current_students: 11,
    email: "mr.martinez@example.com",
    phone: "+9876543215",
  },
  {
    id: 7,
    name: "Dr. Garcia",
    role: "Tutor",
    department: "Medicine",
    created_date: "2020-07-01",
    status: "active",
    current_year: 2,
    current_students: 10,
    email: "dr.garcia@example.com",
    phone: "+9876543216",
  },
  {
    id: 8,
    name: "Prof. Martinez",
    role: "Tutor",
    department: "Law",
    created_date: "2020-08-01",
    status: "offline",
    current_year: 4,
    current_students: 13,
    email: "prof.martinez@example.com",
    phone: "+9876543217",
  },
  {
    id: 9,
    name: "Mr. Lee",
    role: "Tutor",
    department: "Engineering",
    created_date: "2020-09-01",
    status: "active",
    current_year: 3,
    current_students: 9,
    email: "mr.lee@example.com",
    phone: "+9876543218",
  },
  {
    id: 10,
    name: "Dr. Walker",
    role: "Tutor",
    department: "Medicine",
    created_date: "2020-10-01",
    status: "active",
    current_year: 5,
    current_students: 10,
    email: "dr.walker@example.com",
    phone: "+9876543219",
  },
];

export const STAFF_OBJECTS = [
  {
    id: 1,
    name: "Alice Green",
    role: "Staff",
    department: "Administration",
    created_date: "2018-01-01",
    status: "active",
    email: "alice.green@example.com",
    phone: "+1122334455",
  },
  {
    id: 2,
    name: "Bob White",
    role: "Staff",
    department: "Operations",
    created_date: "2018-02-01",
    status: "active",
    email: "bob.white@example.com",
    phone: "+1122334456",
  },
  {
    id: 3,
    name: "Charlie Blue",
    role: "Staff",
    department: "Human Resources",
    created_date: "2018-03-01",
    status: "away",
    email: "charlie.blue@example.com",
    phone: "+1122334457",
  },
  {
    id: 4,
    name: "David Black",
    role: "Staff",
    department: "Finance",
    created_date: "2018-04-01",
    status: "offline",
    email: "david.black@example.com",
    phone: "+1122334458",
  },
  {
    id: 5,
    name: "Eva Red",
    role: "Staff",
    department: "Student Services",
    created_date: "2018-05-01",
    status: "active",
    email: "eva.red@example.com",
    phone: "+1122334459",
  },
  {
    id: 6,
    name: "Frank Yellow",
    role: "Staff",
    department: "Admin Support",
    created_date: "2018-06-01",
    status: "active",
    email: "frank.yellow@example.com",
    phone: "+1122334460",
  },
  {
    id: 7,
    name: "Grace Purple",
    role: "Staff",
    department: "IT Support",
    created_date: "2018-07-01",
    status: "away",
    email: "grace.purple@example.com",
    phone: "+1122334461",
  },
  {
    id: 8,
    name: "Hank Pink",
    role: "Staff",
    department: "Operations",
    created_date: "2018-08-01",
    status: "offline",
    email: "hank.pink@example.com",
    phone: "+1122334462",
  },
  {
    id: 9,
    name: "Ivy Orange",
    role: "Staff",
    department: "Finance",
    created_date: "2018-09-01",
    status: "active",
    email: "ivy.orange@example.com",
    phone: "+1122334463",
  },
  {
    id: 10,
    name: "Jack Brown",
    role: "Staff",
    department: "Admin Support",
    created_date: "2018-10-01",
    status: "active",
    email: "jack.brown@example.com",
    phone: "+1122334464",
  },
];

export const NavLinks = ["Home", "Allocate", "Blog", "Message", "Meeting"];
